### ISSUE TITLE
shortest_paths error: could not find function "rst_xmin"

### ISSUE THREAD

**Issue by joshweiland** [ChristianDueben/spaths#1]
I am trying to run Tobler's hiking function, and when I try to run shortest_paths with both  `dist_comp = "terra", tr_fun = fn`,  I get the following error: 

> Error in rst_xmin(crd_cell_numbers%%rst_ncol) : could not find function "rst_xmin"

When I run this with just  `dist_comp = "terra"` or `tr_fun = fn`, it does not throw an error.

This should be reproducible with the code below.

Poking around the code for this, there is only one line that contains `rst_xmin(crd_cell` or `rst_xmin (crd_cell`, and I'm thinking it is supposed to have an operator between them - "+" or "-" or something, but I'm not sure which one it would be to suggest an edit.

Thanks (and this is the first time I've submitted anything to github - I hope I've given everything you need.)

```
library(spaths)

# Generate example data
set.seed(2L)
input_grid <- terra::rast(crs = "epsg:4326", resolution = 2,
                          vals = sample(c(1L, NA_integer_), 
                                        16200L, TRUE, c(0.8, 0.2)))
origin_pts <- rnd_locations(5L, output_type = "SpatVector")
origin_pts$name <- sample(letters, 5)
destination_pts <- rnd_locations(5L, output_type = "SpatVector")

fn <- function(d, v1, v2){v2 +v1 + d}

# Compute distances
a <- shortest_paths(input_grid, origin_pts, destination_pts,
                    dist_comp = "terra",
                    tr_fun = fn)
```

**Comment by cdueben** [comment]
Thanks. There is indeed a + missing. I will upload a new version later today.

**Comment by cdueben** [comment]
The update is now online. Install with `devtools::install_github("ChristianDueben/spaths", build_vignettes = T)`.
